app = 'backend-bitter-fog-3086'
primary_region = 'gru'
console_command = 'php /var/www/html/artisan tinker'

[build]
[build.args]
NODE_VERSION = '18'
PHP_VERSION = '8.3'

[env]
FRONTEND_URL = "https://www.makeevento.com.br"

APP_NAME = "Make Evento"
APP_ENV = 'production'
APP_DEBUG = 'true'
APP_TIMEZONE = 'UTC'
APP_URL = 'http://localhost'

LOG_CHANNEL = 'stderr'
LOG_LEVEL = 'info'
LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'

DB_CONNECTION = "pgsql"

SESSION_DRIVER = 'database'
SESSION_DOMAIN = '.makeevento.com.br'
SESSION_SECURE_COOKIE = 'true'

MAIL_MAILER = 'resend'
MAIL_FROM_ADDRESS = 'cto@makeevento.com.br'
MAIL_FROM_NAME = 'Make Evento'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[http_service.concurrency]
type = 'requests'
soft_limit = 200

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[deploy]
release_command = "php /var/www/html/artisan migrate --force"
